//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EvalDetails = new HashSet<EvalDetail>();
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string Password { get; set; }
        public string EmployeeName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string MinistryofEducationaCode { get; set; }
        public Nullable<int> EduProvinceId { get; set; }
        public Nullable<int> EduDepartmentId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remarks { get; set; }
    
        public virtual EduDepartment EduDepartment { get; set; }
        public virtual EduProvince EduProvince { get; set; }
        public virtual MinistryofEducation MinistryofEducation { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvalDetail> EvalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual EduMinistry EduMinistry { get; set; }
    }
}
