//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVEEntities : DbContext
    {
        public EVEEntities()
            : base("name=EVEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<EduDepartment> EduDepartments { get; set; }
        public virtual DbSet<EduProvince> EduProvinces { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EvalCriteria> EvalCriterias { get; set; }
        public virtual DbSet<EvalDetail> EvalDetails { get; set; }
        public virtual DbSet<EvalGuide> EvalGuides { get; set; }
        public virtual DbSet<EvalMaster> EvalMasters { get; set; }
        public virtual DbSet<EvalResult> EvalResults { get; set; }
        public virtual DbSet<EvalStandard> EvalStandards { get; set; }
        public virtual DbSet<EvalState> EvalStates { get; set; }
        public virtual DbSet<EvalType> EvalTypes { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<MinistryofEducation> MinistryofEducations { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SchoolLevel> SchoolLevels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<EduLevel> EduLevels { get; set; }
        public virtual DbSet<EduMinistry> EduMinistries { get; set; }
    }
}
