//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form()
        {
            this.UserGroup_Form = new HashSet<UserGroup_Form>();
        }
    
        public string FormCode { get; set; }
        public string FormName { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> Idx { get; set; }
        public string Remarks { get; set; }
    
        public virtual FormGroup FormGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup_Form> UserGroup_Form { get; set; }
    }
}
