//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup_Form
    {
        public string UserGroupCode { get; set; }
        public string FormCode { get; set; }
        public string Remarks { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
